services:
  postgres:
    image: postgres:16-alpine
    container_name: pingou_postgres
    environment:
      POSTGRES_USER: pingoubot
      POSTGRES_PASSWORD: pingou123
      POSTGRES_DB: pingou
    ports: 
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: